[auth]
users = { "farooq9893@gmail.com" = "12345", "partner@gmail.com" = "abcde" }

[gcp_service_account]
type = "service_account"
project_id = "swingscreener-475517"
private_key_id = "8407a0744179f720c89fb494cbbf92bcd50d54ae"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDkeXLZh0FqOLNW
dAJfgOTUF9kFZcDrdhPZ3VchhAjhdHHSe/RTNo3WsUhOJNEA7jqNdlSYzsJuCMg0
soiCpYpZcSwQ4boQCK23dGa1N0VmaIihEq5NOo3OYgkewWr5qOR5vxsnPswdyjz/
qGCdx0A0VELY6lerHHmwF7jLei4s5EVn5N8ue+rrEP3Be9HRXLS/v3kStj+X+hko
M10qQWejjkBSjJ/lJDryHGUMUQ+VTUxBmPVlPHbkMzeP+Or9K2sC+Z0iadGNeEQ4
nqz9e1yLHr7KCX1KJipE4eU+rp8OeLh2uka2nYI6BBV8PIjwbKFoavpaHZXuSa7f
3HqONarjAgMBAAECggEAIGfBYcJiBX4z9t0kFluibm/7eLKCobhGVIOk/2dKGIAl
l2Rmtllp1hD1tRpaXTbCLfJMnr0krT/9oCElD4gJ5BRohZ8efsuxp/A7PmoFI+NL
uFzSmrg6s2e1l3EjinQ+rliWsgL20dAvcADNGKkmyBqeE0TEWSFZeR/ENsgGPe4r
PETr/yW80zpWm+O+t8Y6cOI3g+G9/BZa+qGE22TZIDSgEdhAq4W60nGlMvfcEIMT
h9qFifoHOPZFKxrmUqqqF7RJ6/9NZMNJaUFzvU6uyiDOxxPYKXTQrH9MAO/lukE/
8UWMbCQq2nJ8vuSqTvbYvzpcBRKWdRUgJNbcFUI8UQKBgQD8dqogDX8nHr1BsHKe
4LYcNV3ULjBeq4+dxN7JEEvuX0dsc5wipNOZR1pjMQa4l89pGMhXQcc06b1QDu4q
XRPjwTR8dcRU/hQTTjfGcUNpdvGGOUAJpInntchCw8EmdNxmLcfd1qfuHEMG5BJV
yrwQd3StTDEPvaIS3YXylY7ovwKBgQDnrMJLa1YSJwOdMkI1ucgwiNuVVrDBBIhA
bHqBygs8IlEQr6b/GkeImabAdUTSU1nAtTv89OOzG02UxUk2Tz3vltw8QyZy60j+
kxxifycS1qS5AA12JRQdEUbTCYSKhAKaJt2UNs5xghgIzz594nCytEATYaY3bseY
pm9BcgrC3QKBgBHc34qnCdEdxqxILMP7CEeUqw/hOMDqCJ5UGKNHSOgTy7zrrSdy
XBpjRwzvohcbfqxj+YDbAZpH04I/nDBZJ5gcynbn6j1NQORgy2d6ChgDN3GUyWgl
QTCo1wOKUDdFW3bLVHHoxzb8vu1U48s4LfhIS3QbiPkhJL+K9vhEBrmHAoGAJIxx
nnpRes2i2VLLdTRY66c7lQS3H8w6PoeekAky2orDZTGA0+/uZxNuZiBZ+iBiIW+2
BgMQRPpCs/ynvySjLcAMAInLcAfEXT0SFkve+y7Xj8P9W60fzjIijTqMKVoIGw+U
l0RKL0gJyKIBRtTJWLfs/+HA2i/k1yUymg2GuxUCgYEA5hWBYBsdCrwo+mzeccVh
hhn1+bcRrGw/q3qm70nyE+TYEJNN9sG0h/38y7ZTRCpGYcYaJ2TIAZd4C68JqgcN
MB6nYq/18QL9BS3Dp0C6EqRC+GNLO8XUgq0Q0ghP3iqBEY+m3RkBiKGS80vcMA3U
ZdvIKdx3Xt/l/g4sLoRMnl4=
-----END PRIVATE KEY-----"""
client_email = "swingscreener@swingscreener-475517.iam.gserviceaccount.com"
client_id = "117526066419446361465"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/swingscreener%40swingscreener-475517.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
